import Head from 'next/head'
import { BsFillMoonStarsFill } from "react-icons/bs"; 
import { AiOutlineGithub, AiFillLinkedin } from "react-icons/ai"; 

export default function Home() {
  return (
    <div>
      <Head>
        <title>Alexis Herrera</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl'>Lorem Ipsum</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li><a className='bg-cyan-500 text-white px-4 py-2 rounded ml-8' href="#">Resume</a></li>
            </ul>
          </nav>
          <div>
            <h2>Alexis Herrera</h2>
            <h3>Father | Veteran | Developer</h3>
            <p>Highly adaptable and detail-oriented security professional turned software engineer well-versed in analyzing user needs and developing software to meet diverse needs. Innovative and technically-astute facilitator of solutions accustomed to working with global teams. Enthusiastic and self motivated learner that is committed to personal development and keeping up with industry trends.</p>
          </div>
        </section>
      </main>

      
    </div>
  )
}
